#!/usr/bin/env python3
"""Phase H: machine-generated axiom report for every registered theorem.

Reads proofs_registry.yaml, generates a throwaway Lean audit file that
issues `#print axioms` for each registered lean4_theorem and
lean4_theorem_universal, runs `lake env lean` on it, and parses the
output into a structured JSON report plus a plain-text transcript.

Outputs (under lean4/generated/):
  axiom_report.json  -- { theorem_name: [axiom1, axiom2, ...] }
  axiom_report.txt   -- raw #print axioms transcript
"""
from __future__ import annotations
import json
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.stderr.write(
        "ERROR: PyYAML is required by this script.  Install it via\n"
        "  pip install pyyaml>=6.0\n"
        "or install the full dependency set with\n"
        "  pip install -r requirements.txt\n"
    )
    sys.exit(2)

import os

LEAN4_ROOT = Path(__file__).resolve().parent.parent
KSTAR_ROOT = LEAN4_ROOT.parent
REGISTRY = KSTAR_ROOT / "proofs_registry.yaml"
GENERATED = LEAN4_ROOT / "generated"
# PID-qualified scratch file so concurrent invocations (e.g. CI + local dev
# at the same time) don't race on the same file and unlink each other.
# The scratch lives OUTSIDE the KstarFormal/ tree so Lake's default library
# target doesn't pick it up as a compilable module during `lake build`.
SCRATCH_DIR = LEAN4_ROOT / "_scratch"
AUDIT_LEAN = SCRATCH_DIR / f"axiom_audit_{os.getpid()}.lean"

AXIOMS_BLOCK_RE = re.compile(
    r"'([^']+)' depends on axioms: \[([^\]]*)\]", re.DOTALL
)

# Namespaces used by `#print axioms` targets that are declared inside
# `namespace ... end`. We open them in the audit file so short names resolve.
AUDIT_OPEN_NAMESPACES = [
    "KstarFormal.QaryGram",
    "KstarFormal.WeightSatAllN",
]


def load_theorem_names() -> list[str]:
    """Return unique (ordered) list of all lean4_theorem / _universal names."""
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    names: list[str] = []
    seen: set[str] = set()
    for stmt in data.get("statements", []):
        for key in ("lean4_theorem", "lean4_theorem_universal"):
            tname = stmt.get(key)
            if tname and tname not in seen:
                seen.add(tname)
                names.append(tname)
    return names


def write_audit_file(names: list[str]) -> None:
    lines = [
        "/-",
        "  Auto-generated by scripts/dump_axioms.py. Do not edit by hand.",
        "  Regenerate via `python scripts/dump_axioms.py` from lean4/.",
        "-/",
        "import KstarFormal",
        "",
    ]
    for ns in AUDIT_OPEN_NAMESPACES:
        lines.append(f"open {ns}")
    lines.append("")
    for n in names:
        lines.append(f"#print axioms {n}")
    SCRATCH_DIR.mkdir(exist_ok=True, parents=True)
    AUDIT_LEAN.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_lean_audit() -> tuple[int, str]:
    """Invoke `lake env lean` on the audit file.

    Returns `(returncode, combined_output)`.  A non-zero returncode
    usually means Lean could not elaborate one or more
    `#print axioms` targets (unknown identifier, etc.); the partial
    output is still parseable.
    """
    # Use POSIX-style path for cross-platform compatibility with lake
    # on Windows (some Lean-side tooling is stricter about separators).
    rel = AUDIT_LEAN.relative_to(LEAN4_ROOT).as_posix()
    try:
        result = subprocess.run(
            ["lake", "env", "lean", rel],
            cwd=LEAN4_ROOT,
            capture_output=True,
            text=True,
            shell=False,
            timeout=600,
        )
    except subprocess.TimeoutExpired as e:
        return -1, f"[dump_axioms] lake env lean timed out after 600s: {e}"
    except FileNotFoundError as e:
        return -1, f"[dump_axioms] lake not found on PATH: {e}"
    return result.returncode, (result.stdout or "") + (result.stderr or "")


def parse_axioms(raw: str) -> dict[str, list[str]]:
    """Parse multi-line `#print axioms` blocks.

    Lean wraps long axiom lists across lines; we match the full
    `'name' depends on axioms: [...]` block non-greedily with DOTALL.
    """
    out: dict[str, list[str]] = {}
    for m in AXIOMS_BLOCK_RE.finditer(raw):
        name = m.group(1)
        axioms_blob = m.group(2)
        # Split on commas, strip whitespace + newlines from each entry.
        axioms = [a.strip() for a in axioms_blob.split(",") if a.strip()]
        out[name] = axioms
    return out


def _atomic_write_text(path: Path, payload: str) -> None:
    import tempfile
    path.parent.mkdir(exist_ok=True, parents=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(payload)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def write_outputs(raw: str, axioms: dict[str, list[str]]) -> None:
    _atomic_write_text(GENERATED / "axiom_report.txt", raw)
    _atomic_write_text(
        GENERATED / "axiom_report.json",
        json.dumps(axioms, indent=2, sort_keys=True) + "\n",
    )


def main() -> int:
    names = load_theorem_names()
    if not names:
        print("ERROR: no lean4_theorem entries found in registry")
        return 2
    print(f"[dump_axioms] {len(names)} theorems to audit")
    write_audit_file(names)
    try:
        rc, raw = run_lean_audit()
        if rc != 0:
            # Partial output is still useful; keep going but warn loudly.
            print(
                f"WARN: `lake env lean` exited {rc}; "
                "the axiom report may be incomplete."
            )
        axioms = parse_axioms(raw)
        # A registry name may parse out under a fully-qualified form
        # (e.g. "KstarFormal.QaryGram.bose_mesner_combinatorial_iff" when
        #  the registry lists the short "bose_mesner_combinatorial_iff").
        # Fold those back so downstream consumers find the registry name.
        # Detect short-name collisions: if multiple qualified names fold
        # to the same short name (which the registry lists), warn and
        # refuse to pick one arbitrarily.
        fold_sources: dict[str, list[str]] = {}
        for qname in list(axioms.keys()):
            short = qname.rsplit(".", 1)[-1]
            if short != qname and short in names:
                fold_sources.setdefault(short, []).append(qname)
        for short, sources in fold_sources.items():
            if len(sources) > 1:
                print(
                    f"WARN: short name {short!r} is ambiguous; "
                    f"resolves to {sources}.  Skipping fold; "
                    "the registry should use fully-qualified names."
                )
                continue
            if short not in axioms:
                axioms[short] = axioms[sources[0]]
        missing = [n for n in names if n not in axioms]
        if missing:
            print(f"WARN: no axiom line parsed for {len(missing)} theorems:")
            for n in missing:
                print(f"  - {n}")
        write_outputs(raw, axioms)
        print(f"[dump_axioms] wrote {GENERATED/'axiom_report.json'}")
        print(f"[dump_axioms] wrote {GENERATED/'axiom_report.txt'}")
        # Exit 1 only if missing theorems AND the Lean invocation itself failed.
        # Pure "missing-name" warnings with rc=0 often stem from private/opaque
        # theorems we can't resolve — not a build regression.
        return 1 if missing else 0
    finally:
        # Always clean up the audit scratch file, even on exception paths.
        try:
            AUDIT_LEAN.unlink()
        except FileNotFoundError:
            pass


if __name__ == "__main__":
    sys.exit(main())
